
CREATE TABLE Sale (id BIGINT NOT NULL, operation BIGINT NOT NULL, stock BIGINT NOT NULL, item BIGINT NOT NULL, amount SMALLINT NOT NULL);
ALTER TABLE Sale MODIFY id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Sale ADD CONSTRAINT fk_operation_Sale_operation FOREIGN KEY(operation) REFERENCES Operation(id);
ALTER TABLE Sale ADD CONSTRAINT fk_stock_Sale_stock FOREIGN KEY(stock) REFERENCES Stock(id);
ALTER TABLE Sale ADD CONSTRAINT fk_item_Sale_item FOREIGN KEY(item) REFERENCES CatalogItem(id);

